In [2]:
from data_process import *
#from models import *
#from utility import *
#from train_evaluate import *
import pandas as pd
import os
from tqdm import tqdm

ModuleNotFoundError: No module named 'torch'

In [2]:
#CHANGE THE SKIP TOKEN

#st = sequence
#lst = 
#a = next token
#user_id = user
#skip = skip
#buy = was the next a hit
#display(pd.read_csv('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/transition_store_test.csv'))

st  lst      a  buy  \
0                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]    1    151    1   
1                    [0, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0]    1    150    1   
2                  [0, 151, 150, 0, 0, 0, 0, 0, 0, 0, 0]    2    149    1   
3                [0, 151, 150, 149, 0, 0, 0, 0, 0, 0, 0]    3    148    1   
4              [0, 151, 150, 149, 148, 0, 0, 0, 0, 0, 0]    4    147    1   
...                                                  ...  ...    ...  ...   
19314          [5, 21195, 21194, 0, 0, 0, 0, 0, 0, 0, 0]    2  21193    1   
19315      [5, 21195, 21194, 21193, 0, 0, 0, 0, 0, 0, 0]    3  21192    1   
19316  [5, 21195, 21194, 21193, 21192, 0, 0, 0, 0, 0, 0]    4  21191    1   
19317  [5, 21195, 21194, 21193, 21192, 21191, 0, 0, 0...    5  21190    1   
19318  [5, 21195, 21194, 21193, 21192, 21191, 21190, ...    6  21189    1   

       user_id                            skip  
0            0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  
1            0  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]  
2            0  [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]  
3            0  [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]  
4            0  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]  
...        ...                             ...  
19314        5  [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]  
19315        5  [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]  
19316        5  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]  
19317        5  [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]  
19318        5  [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]  

[19319 rows x 6 columns]

In [ ]:
m = DataModule('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/', 32)

In [2]:
filepath = '/mnt/data2/pavans/pavans/training_set'
test_file = os.listdir(filepath)[1]

df = pd.read_csv(os.path.join(filepath, test_file))
df

session_id  session_position  \
0        10_0000172c-a619-44a1-9284-6f88ba876507                 1   
1        10_0000172c-a619-44a1-9284-6f88ba876507                 2   
2        10_0000172c-a619-44a1-9284-6f88ba876507                 3   
3        10_0000172c-a619-44a1-9284-6f88ba876507                 4   
4        10_0000172c-a619-44a1-9284-6f88ba876507                 5   
...                                          ...               ...   
3257778  10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98                16   
3257779  10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98                17   
3257780  10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98                18   
3257781  10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98                19   
3257782  10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98                20   

         session_length                          track_id_clean  skip_1  \
0                    20  t_10a02b6d-bd97-40e0-907a-b964f0e8c3e7   False   
1                    20  t_79c5d73d-9949-4a25-a98e-9839a616d400    True   
2                    20  t_612e16f4-14e2-4e4c-9b97-14ab82240a47    True   
3                    20  t_cd661951-833f-4392-b101-f83568a0ae70    True   
4                    20  t_8f9f2397-334b-48ee-9120-96d9ddf32f92    True   
...                 ...                                     ...     ...   
3257778              20  t_363c666e-73aa-4b97-8c65-667cd0e190a0   False   
3257779              20  t_e6dbaa5a-419a-4b45-a1c1-09867a88f4ec   False   
3257780              20  t_eacd7e86-70a8-4207-a412-238cc55c1112   False   
3257781              20  t_2a55e695-7894-42aa-b920-52d1cbaf164c   False   
3257782              20  t_a66ea088-b357-449a-8a1e-64dd0b8d6cb5   False   

         skip_2  skip_3  not_skipped  context_switch  no_pause_before_play  \
0          True    True        False               0                     0   
1          True    True        False               0                     1   
2          True    True        False               0                     1   
3          True    True        False               0                     1   
4          True    True        False               0                     1   
...         ...     ...          ...             ...                   ...   
3257778   False   False         True               0                     1   
3257779   False   False         True               0                     1   
3257780   False   False         True               0                     1   
3257781   False   False         True               0                     0   
3257782   False    True        False               0                     0   

         ...  long_pause_before_play  hist_user_behavior_n_seekfwd  \
0        ...                       0                             0   
1        ...                       0                             0   
2        ...                       0                             0   
3        ...                       0                             0   
4        ...                       0                             0   
...      ...                     ...                           ...   
3257778  ...                       0                             0   
3257779  ...                       0                             0   
3257780  ...                       0                             0   
3257781  ...                       1                             0   
3257782  ...                       1                             0   

         hist_user_behavior_n_seekback  hist_user_behavior_is_shuffle  \
0                                    0                          False   
1                                    0                          False   
2                                    0                          False   
3                                    0                          False   
4                                    0                          False   
...                                ...                            ...   
3257778

In [ ]:
sessions = list()
skips = list()
vocab = set()
session_ids = list()
cols = ['session_position', 'track_id_clean', 'skip_level'] #+ ['skip_1', 'skip_2', 'skip_3']
#skip_level = lambda df_: [4 - x for x in range(1, 4) if df_[f'skip_{x}'].bool() else 0] #0 - 3 in order of most severe skip
for s, df_s in tqdm(df.groupby(['session_id'])):
    df_s.sort_values(by = ['session_position'], axis=0, inplace=True)
    df_s['skip_level'] = ((df_s['skip_1'].astype(int) + df_s['skip_2'].astype(int) + df_s['skip_3'].astype(int)))
    df_s = df_s[cols]
    sessions.append(df_s['track_id_clean'].to_list())
    skips.append(df_s['skip_level'])
    vocab = vocab.union(set(sessions[-1]))
    session_ids.append(s)
print(len(session_ids) == len(sessions))

 20%|██        | 39779/195829 [02:51<18:27, 140.86it/s]

In [21]:
print( 3 % 4)

3


In [1]:
import torch

In [9]:
x = torch.linspace(0,21, 20).long()
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 21])


In [12]:
print(torch.unique(x, return_inverse=True)[1])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [23]:
y = torch.randint(67, (128,20))

In [32]:
print(torch.unique(y, return_inverse=True)[1])

tensor([[22, 17, 50,  ..., 43,  7,  2],
        [45, 24,  4,  ..., 50, 44,  8],
        [51, 59, 21,  ..., 36,  0,  7],
        ...,
        [44, 65, 26,  ..., 23, 26, 19],
        [23, 45, 12,  ...,  4, 22,  7],
        [58,  2, 36,  ..., 24,  7, 30]])


In [233]:
import torch 
PADDING_ITEM = 0
mask_token = 2
def _mask_tracks(X, prop=0.15):
        Y = X[X != PADDING_ITEM]
        indices = torch.randperm(torch.numel(Y))
        indices = indices[:int(0.15//(1/indices.shape[0]))]
        Y[indices] = mask_token

        X[X != PADDING_ITEM] = Y

        return X

def _mask_tracks2(X, prop=0.15):
        X = X.detach().clone()
        dist = torch.ones(X.shape)
        dist[X == PADDING_ITEM] = 0
        #indices = torch.clamp(torch.multinomial(dist, int(X.shape[1] // (1/prop))), min=torch.ones((X.shape[0], 1)), 
                              #max=(torch.argmin(X, dim=1) - 1).unsqueeze(dim=-1)).long()
        indices = torch.multinomial(dist, 2)
        
        batch_idx = torch.tile(torch.linspace(0, X.shape[0] - 1, steps = X.shape[0]), (indices.shape[1],1)).long().T

        X[batch_idx, indices] = mask_token

        last_item = torch.argmin(X, dim=1)
        X[range(X.shape[0]), last_item] = mask_token

        return X

In [236]:
y = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
z = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
m = _mask_tracks2(y)
#print(m)
#print(torch.argwhere(m == 2))
masked_targets = y[m == mask_token].view(64, 3)
print(masked_targets.shape)
last_item = torch.argmin(y, dim=1) - 1
#print(y[range(y.shape[0]), last_item])
masked_targets[:, -1] = z[range(z.shape[0]), last_item]

print(m)
print(masked_targets)

torch.Size([64, 3])
tensor([[1.3867e+05, 4.7810e+04, 1.1316e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9929e+05, 1.6205e+05, 5.1511e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9202e+05, 2.3774e+05, 2.8134e+05,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [7.6040e+04, 1.9671e+05, 2.5400e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.6113e+05, 1.8642e+05, 2.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.7354e+05, 2.0000e+00, 3.3003e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])
tensor([[256447.,   4439., 287229.],
        [ 95003., 137267., 195677.],
        [113269., 198033.,  71481.],
        [237428.,  48155., 115184.],
        [ 86473., 104540., 210444.],
        [171052.,  68637.,  79306.],
        [123518., 211093., 189224.],
        [182003., 209677., 145793.],
        [200162., 133951., 264391.],
        [121833.,  96787., 124801.],
        [25480

In [229]:
print(int((21 - 3) // (1/0.15)))

2


192