In [6]:
from data_process import *
#from models import *
#from utility import *
#from train_evaluate import *
import pandas as pd
import os
from tqdm import tqdm

In [2]:
#CHANGE THE SKIP TOKEN

#st = sequence
#lst = 
#a = next token
#user_id = user
#skip = skip
#buy = was the next a hit
#display(pd.read_csv('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/transition_store_test.csv'))

,st,lst,a,buy,user_id,skip
0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,151,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,"[0, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,150,1,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,"[0, 151, 150, 0, 0, 0, 0, 0, 0, 0, 0]",2,149,1,0,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
3,"[0, 151, 150, 149, 0, 0, 0, 0, 0, 0, 0]",3,148,1,0,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
4,"[0, 151, 150, 149, 148, 0, 0, 0, 0, 0, 0]",4,147,1,0,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...
19314,"[5, 21195, 21194, 0, 0, 0, 0, 0, 0, 0, 0]",2,21193,1,5,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
19315,"[5, 21195, 21194, 21193, 0, 0, 0, 0, 0, 0, 0]",3,21192,1,5,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
19316,"[5, 21195, 21194, 21193, 21192, 0, 0, 0, 0, 0, 0]",4,21191,1,5,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
19317,"[5, 21195, 21194, 21193, 21192, 21191, 0, 0, 0...",5,21190,1,5,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]"


In [ ]:
m = DataModule('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/', 32)

In [2]:
filepath = '/mnt/data2/pavans/pavans/training_set'
test_file = os.listdir(filepath)[1]

df = pd.read_csv(os.path.join(filepath, test_file))
df

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,long_pause_before_play,hist_user_behavior_n_seekfwd,hist_user_behavior_n_seekback,hist_user_behavior_is_shuffle,hour_of_day,date,premium,context_type,hist_user_behavior_reason_start,hist_user_behavior_reason_end
0,10_0000172c-a619-44a1-9284-6f88ba876507,1,20,t_10a02b6d-bd97-40e0-907a-b964f0e8c3e7,False,True,True,False,0,0,...,0,0,0,False,20,2018-07-24,False,user_collection,trackdone,fwdbtn
1,10_0000172c-a619-44a1-9284-6f88ba876507,2,20,t_79c5d73d-9949-4a25-a98e-9839a616d400,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
2,10_0000172c-a619-44a1-9284-6f88ba876507,3,20,t_612e16f4-14e2-4e4c-9b97-14ab82240a47,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
3,10_0000172c-a619-44a1-9284-6f88ba876507,4,20,t_cd661951-833f-4392-b101-f83568a0ae70,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
4,10_0000172c-a619-44a1-9284-6f88ba876507,5,20,t_8f9f2397-334b-48ee-9120-96d9ddf32f92,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,backbtn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257778,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,16,20,t_363c666e-73aa-4b97-8c65-667cd0e190a0,False,False,False,True,0,1,...,0,0,1,False,11,2018-07-25,True,catalog,fwdbtn,trackdone
3257779,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,17,20,t_e6dbaa5a-419a-4b45-a1c1-09867a88f4ec,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257780,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,18,20,t_eacd7e86-70a8-4207-a412-238cc55c1112,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257781,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,19,20,t_2a55e695-7894-42aa-b920-52d1cbaf164c,False,False,False,True,0,0,...,1,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone


In [ ]:
sessions = list()
skips = list()
vocab = set()
session_ids = list()
cols = ['session_position', 'track_id_clean', 'skip_level'] #+ ['skip_1', 'skip_2', 'skip_3']
#skip_level = lambda df_: [4 - x for x in range(1, 4) if df_[f'skip_{x}'].bool() else 0] #0 - 3 in order of most severe skip
for s, df_s in tqdm(df.groupby(['session_id'])):
    df_s.sort_values(by = ['session_position'], axis=0, inplace=True)
    df_s['skip_level'] = ((df_s['skip_1'].astype(int) + df_s['skip_2'].astype(int) + df_s['skip_3'].astype(int)))
    df_s = df_s[cols]
    sessions.append(df_s['track_id_clean'].to_list())
    skips.append(df_s['skip_level'])
    vocab = vocab.union(set(sessions[-1]))
    session_ids.append(s)
print(len(session_ids) == len(sessions))

 20%|██        | 39779/195829 [02:51<18:27, 140.86it/s]

In [21]:
print( 3 % 4)

3


In [1]:
import torch

In [9]:
x = torch.linspace(0,21, 20).long()
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 21])


In [12]:
print(torch.unique(x, return_inverse=True)[1])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [23]:
y = torch.randint(67, (128,20))

In [32]:
print(torch.unique(y, return_inverse=True)[1])

tensor([[22, 17, 50,  ..., 43,  7,  2],
        [45, 24,  4,  ..., 50, 44,  8],
        [51, 59, 21,  ..., 36,  0,  7],
        ...,
        [44, 65, 26,  ..., 23, 26, 19],
        [23, 45, 12,  ...,  4, 22,  7],
        [58,  2, 36,  ..., 24,  7, 30]])


In [233]:
import torch 
PADDING_ITEM = 0
mask_token = 2
def _mask_tracks(X, prop=0.15):
        Y = X[X != PADDING_ITEM]
        indices = torch.randperm(torch.numel(Y))
        indices = indices[:int(0.15//(1/indices.shape[0]))]
        Y[indices] = mask_token

        X[X != PADDING_ITEM] = Y

        return X

def _mask_tracks2(X, prop=0.15):
        X = X.detach().clone()
        dist = torch.ones(X.shape)
        dist[X == PADDING_ITEM] = 0
        #indices = torch.clamp(torch.multinomial(dist, int(X.shape[1] // (1/prop))), min=torch.ones((X.shape[0], 1)), 
                              #max=(torch.argmin(X, dim=1) - 1).unsqueeze(dim=-1)).long()
        indices = torch.multinomial(dist, 2)
        
        batch_idx = torch.tile(torch.linspace(0, X.shape[0] - 1, steps = X.shape[0]), (indices.shape[1],1)).long().T

        X[batch_idx, indices] = mask_token

        last_item = torch.argmin(X, dim=1)
        X[range(X.shape[0]), last_item] = mask_token

        return X

In [236]:
y = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
z = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
m = _mask_tracks2(y)
#print(m)
#print(torch.argwhere(m == 2))
masked_targets = y[m == mask_token].view(64, 3)
print(masked_targets.shape)
last_item = torch.argmin(y, dim=1) - 1
#print(y[range(y.shape[0]), last_item])
masked_targets[:, -1] = z[range(z.shape[0]), last_item]

print(m)
print(masked_targets)

torch.Size([64, 3])
tensor([[1.3867e+05, 4.7810e+04, 1.1316e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9929e+05, 1.6205e+05, 5.1511e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9202e+05, 2.3774e+05, 2.8134e+05,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [7.6040e+04, 1.9671e+05, 2.5400e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.6113e+05, 1.8642e+05, 2.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.7354e+05, 2.0000e+00, 3.3003e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])
tensor([[256447.,   4439., 287229.],
        [ 95003., 137267., 195677.],
        [113269., 198033.,  71481.],
        [237428.,  48155., 115184.],
        [ 86473., 104540., 210444.],
        [171052.,  68637.,  79306.],
        [123518., 211093., 189224.],
        [182003., 209677., 145793.],
        [200162., 133951., 264391.],
        [121833.,  96787., 124801.],
        [25480

In [229]:
print(int((21 - 3) // (1/0.15)))

2


In [1]:
import pandas as pd

df = pd.read_csv('/home/pavans/dev/sequential-music-recommendation/datasets/lfm/plays_with_session_with_skip_2.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,Fuck Me Im Famous (Pacha Ibiza)-09-28-2007,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Composition 0919 (Live_2009_4_15),1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc2 (Live_2009_4_15),1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Hibari (Live_2009_4_15),1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc1 (Live_2009_4_15),1,1


In [4]:
df['track-name'] = df['track-name'].factorize()[0]
df.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,0,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,1,1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,2,1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,3,1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,4,1,1


In [7]:
groups = df.groupby('Session_id')
groups.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,0,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,1,1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,2,1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,3,1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,4,1,1
...,...,...,...,...,...,...,...,...,...,...
19150842,19150842,19150842,user_001000,2008-01-27 23:26:56+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,936b1924-be61-40c8-85b1-a0ddd03c47b6,83486,1042297,1
19150843,19150843,19150843,user_001000,2008-01-27 23:23:26+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,3536ef47-dcdd-4a9b-980f-5febcb655fc9,10039,1042297,1
19150844,19150844,19150844,user_001000,2008-01-27 23:16:30+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,e3820060-90e7-4359-8243-bf32cc6904e7,63929,1042297,1
19150845,19150845,19150845,user_001000,2008-01-27 23:13:33+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,be2d253d-2b90-4703-b20a-6ca9531e251f,153924,1042297,1


In [11]:
sessions = groups['track-name'].apply(list)
skips = groups['skip'].apply(list)
vocab = set(df['track-name'].to_list())
print(len([s for s in sessions if len(s) > 5]))

642539


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/pavans/dev/sequential-music-recommendation/datasets/lfm-2b/plays_with_session_with_skip2.csv')

In [5]:
df
df['track-name'] = df['track-name'].factorize()[0]

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
0,0,1000,4154409,14720156,2020-01-01 21:02:17,0,False
1,1,1000,42521726,14720156,2020-01-01 21:03:37,0,False
2,2,1000,22978395,14720156,2020-01-01 21:07:49,0,False
3,3,1000,42103242,14720156,2020-01-01 21:13:37,0,False
4,4,1000,25123379,14720156,2020-01-01 21:15:06,0,False
...,...,...,...,...,...,...,...
30357781,30357781,9998,8302820,19987164,2020-03-20 12:10:24,2223213,False
30357782,30357782,9998,21928646,19987164,2020-03-20 12:15:26,2223213,False
30357783,30357783,9998,37491098,19987164,2020-03-20 12:20:56,2223213,False
30357784,30357784,9998,17792531,19987164,2020-03-20 12:25:16,2223213,False


In [21]:

display(df[df['track-name'] == 682330].sort_values(by='Session_id'))
display(df[df['track-name'] == 278671])
display(df[df['Session_id'] == 171390])

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
2313656,2313656,119957,682330,9370923,2020-02-10 10:06:43,171359,False
2313914,2313914,119957,682330,9370923,2020-02-16 20:45:45,171385,False
2313933,2313933,119957,682330,9370923,2020-02-17 09:37:39,171387,False
2313966,2313966,119957,682330,9370923,2020-02-17 15:13:20,171389,False
2313974,2313974,119957,682330,9370923,2020-02-17 18:42:12,171390,False
2314181,2314181,119957,682330,9370923,2020-02-19 18:17:20,171403,False
2314228,2314228,119957,682330,9370923,2020-02-19 21:16:52,171404,False
2314236,2314236,119957,682330,9370923,2020-02-19 21:43:34,171404,False
2314260,2314260,119957,682330,9370923,2020-02-20 08:46:26,171405,False
2314285,2314285,119957,682330,9370923,2020-02-21 10:06:40,171410,False


,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
733575,733575,10539,278671,20555841,2020-03-13 03:58:08,49439,False
734103,734103,10539,278671,20555841,2020-03-19 15:25:41,49458,False


,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
2313974,2313974,119957,682330,9370923,2020-02-17 18:42:12,171390,False
2313975,2313975,119957,682346,18052563,2020-02-17 18:48:31,171390,False
2313976,2313976,119957,682347,17615673,2020-02-17 18:52:39,171390,False
2313977,2313977,119957,682348,16151311,2020-02-17 18:56:57,171390,False
2313978,2313978,119957,35302,22608282,2020-02-17 18:59:58,171390,False
2313979,2313979,119957,682349,22163350,2020-02-17 19:05:27,171390,False


In [28]:
cols = df.columns
for x in cols:
    df[x] = df[x].apply(type)
    print(df[x].unique())

[<class 'int'>]
[<class 'int'>]
[<class 'int'>]
[<class 'int'>]
[<class 'str'>]
[<class 'int'>]
[<class 'bool'>]


In [29]:
df.apply(type)

Unnamed: 0    <class 'pandas.core.series.Series'>
user          <class 'pandas.core.series.Series'>
track-name    <class 'pandas.core.series.Series'>
album_id      <class 'pandas.core.series.Series'>
timestamp     <class 'pandas.core.series.Series'>
Session_id    <class 'pandas.core.series.Series'>
skip          <class 'pandas.core.series.Series'>
dtype: object

In [7]:
import yaml

with open('config/config-lfm2B.yml', 'r') as file:
        config = yaml.safe_load(file)

In [8]:
data = LfMDataModule(config['data_params']['data_path'], config['data_params']['batch_size'], dev=config['dev'])

vocab: 1500866 sessions:464810 interactions: 7624976


In [9]:
from models import VanillaTransformer
model = VanillaTransformer(**config['model_params'], vocab_size=len(data.vocab)).to('cuda')
model.eval()
torch.cuda.empty_cache()
from tqdm import tqdm
with torch.no_grad():
    for batch in tqdm(data.test_dataloader()):
        batch = tuple([x.cuda() for x in batch])
        '''
        sessions, targets, skip = batch
        skip = skip.long()
        targets = targets.long()
        sessions = model._mask_tracks(sessions, TRAIN=False)
        output_1, x_ = model(sessions)
        output, targets = model.sampled_softmax(output_1, targets)
        output = output.transpose(1, 2)
        target_loss = model.loss(output, targets)
        if torch.isnan(target_loss).any():
            print(output_1, output, targets, skip)
        '''
        loss = model.test_step(batch, 0)
        if torch.isnan(loss).any():
            print(batch)
        
        

  0%|                                                                                                                                                                                                                                                                                                          | 0/3632 [00:00<?, ?it/s]/home/pavans/miniconda3/envs/rec/lib/python3.9/site-packages/pytorch_lightning/core/module.py:416: UserWarning: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
  rank_zero_warn(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3632/3632 [02:54<00:00, 20.85it/s]


In [14]:
counter = 0
for batch in tqdm(data.val_dataloader()):
    if counter > 5:
        break
    for b in batch:
        print(b)
    counter+=1
    

  0%|                                                                                                                                                                                                                                                                                                | 1/3632 [00:03<3:54:04,  3.87s/it]

tensor([[ 768,  769,  770,  ...,    0,    0,    0],
        [ 787,  788,  789,  ...,    0,    0,    0],
        [ 805,  806,  760,  ...,    0,    0,    0],
        ...,
        [9695, 9718, 9853,  ...,    0,    0,    0],
        [9618, 9621, 9619,  ...,    0,    0,    0],
        [9899, 9900, 9842,  ...,    0,    0,    0]], dtype=torch.int32)
tensor([ 393,  803,  820,  833, 1027, 1053, 1059, 1345, 1529, 1545, 1135, 1256,
        1262, 4346, 4602, 4621, 4631, 5116, 5121, 5312, 5338, 5363, 5412, 4382,
        5448, 5467, 5486, 5501, 6064, 6066, 6449, 6289, 6445, 6088, 5973, 6214,
        5649, 6448,  574,  339, 6454, 6440, 6214, 6458,  339, 6088, 5741, 6484,
        6492, 3153, 5610, 6132, 6560, 7106, 7185, 7189, 7272, 7315, 7413, 7452,
        7487, 7501, 7556, 7564, 7391, 7635, 7645, 7433, 7575, 7419, 7704, 7557,
        7331, 7328, 7746, 7782, 7796, 7848, 7868, 7873, 7922, 7900, 7919, 8016,
        7887, 8093, 8113, 8130, 8143, 8159, 8173, 8184, 8191, 8201, 8208, 8229,
        8241, 8

  0%|▍                                                                                                                                                                                                                                                                                                 | 6/3632 [00:04<48:25,  1.25it/s]
